global:
  resolve_timeout: 1m

templates:
  - '/etc/alert_manager/templates/discord_custom.tmpl'

route:
  group_by: ['...']
  group_wait: 0s
  group_interval: 5m
  repeat_interval: 1h
  
  routes:
    - receiver: 'discord'
      group_by: ['...']

  receiver: discord

receivers:
  - name: 'discord'
    discord_configs:
      - webhook_url: DISCORD_WEB_HOOK
        title: '{{ template "discord.title" . }}'
        message: '{{ template "discord.message" . }}'