{
 "title": "Celesta DA Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Data Per Namespace",
   "type": "xychart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "shares_by_namespace{}", "legendFormat": "__auto" }
   ]
  },
  { "title": "Sync Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Local height",
   "type": "stat",
   "description": "Bridge node height",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "local_height", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Local height time",
   "type": "stat",
   "description": "local (bridge node) height block time in seconds",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(local_height_time[1h]) / count_over_time(local_height_time[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network height",
   "type": "stat",
   "description": "Current network height",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "network_height", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Network height block time",
   "type": "stat",
   "description": "Network block time in seconds",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(network_height_time[1h]) / count_over_time(network_height_time[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Local local height gauge",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "targets": [
    { "expr": "local_height{}", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Network height gauge",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "targets": [
    { "expr": "network_height{}", "legendFormat": "{{__name__}}" }
   ]
  },
  { "title": "P2P Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Peers connected",
   "type": "stat",
   "description": "Current network height",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "peers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Peers blocked",
   "type": "stat",
   "description": "Current network height",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "blocked_peers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total received data in GB",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bandwidth_total_out / 1000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total sent data in GB",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bandwidth_total_in / 1000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    { "expr": "peers", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "DA sent/received data in MB/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    { "expr": "bandwidth_rate_in / 1000000", "legendFormat": "received data in MB/s" },
    { "expr": "bandwidth_rate_out / 1000000", "legendFormat": "sent data in MB/s" }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Bridge Node Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "{unit=~\"celestia-[lbf].*.service\"}"
    }
   ]
  }
 ]
}