groups:
  - name: celestia-bridge
    rules:
    - alert: CelestiaBridgeNodeNotRunning
      expr: absent(up{job=~"bridge-.*"})
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "Celestia Bridge Node service is not running (instance {{ $labels.instance }})"
        description: "Celestia Bridge Node service is not running\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: BridgeNodeStuck
      expr: delta(local_height[5m]) != 0
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "Celestia Bridge Node {{ $labels.instance }} is stuck"
        description: "Celestia Bridge Node {{ $labels.instance }} is stuck"

    - alert: LowP2pConnection
      expr: peers < 2
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Celestia Bridge Node {{ $labels.instance }} is having less than 2 peers connected for 5min"
        description: "Celestia Bridge Node {{ $labels.instance }} is currently connected to {{ $value }}"

    - alert: BridgeNodeUnusualBlockTime
      expr: delta(local_height_time[1h]) / count_over_time(local_height_time[1h]) > 24
      for: 1m
      labels:
        severity: info
      annotations:
        summary: "Celestia Bridge Node {{ $labels.instance }} or network block time is more than 24s"
        description: "Celestia Bridge Node {{ $labels.instance }} or network block time is currently at {{ $value }}"

  - name: celestia-core
    rules:
    - alert: CoreNodeStuck
      expr: delta(network_height[5m]) != 0
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "Celestia Core Node {{ $labels.instance }} is stuck"
        description: "Celestia Core Node {{ $labels.instance }} is stuck"

    - alert: CoreNodeUnusualBlockTime
      expr: delta(network_height_time[1h]) / count_over_time(network_height_time[1h])
      for: 1m
      labels:
        severity: info
      annotations:
        summary: "Celestia Core Node {{ $labels.instance }} or network block time is more than 24s"
        description: "Celestia Core Node {{ $labels.instance }} or network block time is currently at {{ $value }}"